### ISSUE TITLE
[jason-ros-paper] add option for selecting some parameters of topics to become percept/beliefs

### ISSUE THREAD

**Issue by maiquelb** [maiquelb/embedded-mas#25]
For example, considering the configuration

```
...
perceptionTopics:         
  - topicName: turtle1/pose
    topicType: turtlesim/Pose
    beliefName: robot_position
```

the topic ```turtleX/pose(x, y, theta, linear_velocity, angular_velocity)``` currently produces the belief ```robot_position(x, y, theta, linear_velocity, angular_velocity)```

This configuration could be extended to 

```
...
perceptionTopics:         
  - topicName: turtle1/pose
    topicType: turtlesim/Pose
    beliefName: robot_position
    interestParams:
       - x
       - y
```
to, then, produce the belief ```robot_position(x, y)```.

If the ```interestParams``` key is omitted, the belief transformation follows the default.
